CPP_SOURCES += $(wildcard $(CCAM_ROOT)/libCCAM/ccam/utils/*.cpp)
CPP_SOURCES += $(wildcard $(CCAM_ROOT)/libCCAM/ccam/voice/*.cpp)
CPP_SOURCES += $(wildcard $(CCAM_ROOT)/libCCAM/ccam/seq/*.cpp)
C_INCLUDES += -I$(CCAM_DIR)